// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('@arco-design/web-vue')['Alert']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACascader: typeof import('@arco-design/web-vue')['Cascader']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    ACheckboxGroup: typeof import('@arco-design/web-vue')['CheckboxGroup']
    ACol: typeof import('@arco-design/web-vue')['Col']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AOption: typeof import('@arco-design/web-vue')['Option']
    APopconfirm: typeof import('@arco-design/web-vue')['Popconfirm']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    AResizeBox: typeof import('@arco-design/web-vue')['ResizeBox']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    AutoBtn: typeof import('./src/components/autoBtn.vue')['default']
    CodeBg: typeof import('./src/components/codeBg.vue')['default']
    ColorfulBtn: typeof import('./src/components/colorfulBtn.vue')['default']
    CusSwitch: typeof import('./src/components/cusSwitch.vue')['default']
    DarkFullPage: typeof import('./src/components/darkFullPage.vue')['default']
    HoverAnswer: typeof import('./src/components/hoverAnswer.vue')['default']
    LightFullPage: typeof import('./src/components/lightFullPage.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    LoadingIcon01: typeof import('./src/components/loadingIcon01.vue')['default']
    LoadingIcon02: typeof import('./src/components/loadingIcon02.vue')['default']
    LoadingIcon03: typeof import('./src/components/loadingIcon03.vue')['default']
    MimicryBtn: typeof import('./src/components/mimicryBtn.vue')['default']
    SettingCard: typeof import('./src/components/settingCard.vue')['default']
    SettingModal: typeof import('./src/components/SettingModal/index.vue')['default']
  }
}
